application-description: API for bank-rest.
application-version: 0.0.1-alpha

spring:
  application:
    name: Bank_REST
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DB:bank_rest}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: POSTGRESQL
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml

app:
  jwt:
    secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui/

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:12345678}
  email: ${ADMIN_EMAIL:admin@email.ru}

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    ru.lidzhiev: DEBUG